import { createSlice, createAsyncThunk, isAnyOf } from "@reduxjs/toolkit"
import { RootState } from "redux/store"
import { IArenaOwner } from "types"
import { SearchEventPayload } from "types/Event"
import arenaAPI from "./arenaAPI"
